name: Release Creation

on:
  push:
    branches:
      - main
      - release/*

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Cache local Maven repository
        uses: actions/cache@v4.0.0
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: 8
          distribution: 'adopt'
          settings-path: ${{ github.workspace }}
      - name: Build with Maven
        run: mvn -B package --file pom.xml -s $GITHUB_WORKSPACE/settings.xml -DskipTests
        env:
          GITHUB_TOKEN: ${{ github.token }}

      # Create the release
      - name: Create Release or Pre-release
        uses: softprops/action-gh-release@master
        with:
          release_name: Checkmarx CxONE Teamcity-Plugin-JDK8
          tag_name: jdk8-release
          files: ./build/target/cxone-teamcity-plugin-jdk8.zip
          generate_release_notes: true

